// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public interface AddProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.AddProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
