// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public interface AddProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.AddProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
