// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public interface GetStockLevelsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.GetStockLevelsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product> 
      getStockList();
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  com.ayo.inventorymanagement.GetStockLevelsResponse.Product getStock(int index);
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  int getStockCount();
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  java.util.List<? extends com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder> 
      getStockOrBuilderList();
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder getStockOrBuilder(
      int index);
}
