// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

/**
 * Protobuf type {@code com.ayo.inventorymanagement.GetStockLevelsResponse}
 */
public  final class GetStockLevelsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.ayo.inventorymanagement.GetStockLevelsResponse)
    GetStockLevelsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetStockLevelsResponse.newBuilder() to construct.
  private GetStockLevelsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetStockLevelsResponse() {
    stock_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetStockLevelsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              stock_ = new java.util.ArrayList<com.ayo.inventorymanagement.GetStockLevelsResponse.Product>();
              mutable_bitField0_ |= 0x00000001;
            }
            stock_.add(
                input.readMessage(com.ayo.inventorymanagement.GetStockLevelsResponse.Product.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        stock_ = java.util.Collections.unmodifiableList(stock_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ayo.inventorymanagement.GetStockLevelsResponse.class, com.ayo.inventorymanagement.GetStockLevelsResponse.Builder.class);
  }

  public interface ProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.GetStockLevelsResponse.Product)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 quantity = 3;</code>
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code com.ayo.inventorymanagement.GetStockLevelsResponse.Product}
   */
  public  static final class Product extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.ayo.inventorymanagement.GetStockLevelsResponse.Product)
      ProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Product.newBuilder() to construct.
    private Product(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Product() {
      id_ = "";
      name_ = "";
      quantity_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Product(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              quantity_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayo.inventorymanagement.GetStockLevelsResponse.Product.class, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 3;
    private int quantity_;
    /**
     * <code>int32 quantity = 3;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (quantity_ != 0) {
        output.writeInt32(3, quantity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (quantity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quantity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ayo.inventorymanagement.GetStockLevelsResponse.Product)) {
        return super.equals(obj);
      }
      com.ayo.inventorymanagement.GetStockLevelsResponse.Product other = (com.ayo.inventorymanagement.GetStockLevelsResponse.Product) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getQuantity()
          == other.getQuantity());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuantity();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ayo.inventorymanagement.GetStockLevelsResponse.Product prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.ayo.inventorymanagement.GetStockLevelsResponse.Product}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.ayo.inventorymanagement.GetStockLevelsResponse.Product)
        com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ayo.inventorymanagement.GetStockLevelsResponse.Product.class, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder.class);
      }

      // Construct using com.ayo.inventorymanagement.GetStockLevelsResponse.Product.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        name_ = "";

        quantity_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor;
      }

      @java.lang.Override
      public com.ayo.inventorymanagement.GetStockLevelsResponse.Product getDefaultInstanceForType() {
        return com.ayo.inventorymanagement.GetStockLevelsResponse.Product.getDefaultInstance();
      }

      @java.lang.Override
      public com.ayo.inventorymanagement.GetStockLevelsResponse.Product build() {
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ayo.inventorymanagement.GetStockLevelsResponse.Product buildPartial() {
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product result = new com.ayo.inventorymanagement.GetStockLevelsResponse.Product(this);
        result.id_ = id_;
        result.name_ = name_;
        result.quantity_ = quantity_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ayo.inventorymanagement.GetStockLevelsResponse.Product) {
          return mergeFrom((com.ayo.inventorymanagement.GetStockLevelsResponse.Product)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ayo.inventorymanagement.GetStockLevelsResponse.Product other) {
        if (other == com.ayo.inventorymanagement.GetStockLevelsResponse.Product.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getQuantity() != 0) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ayo.inventorymanagement.GetStockLevelsResponse.Product) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>int32 quantity = 3;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>int32 quantity = 3;</code>
       */
      public Builder setQuantity(int value) {
        
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 quantity = 3;</code>
       */
      public Builder clearQuantity() {
        
        quantity_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.ayo.inventorymanagement.GetStockLevelsResponse.Product)
    }

    // @@protoc_insertion_point(class_scope:com.ayo.inventorymanagement.GetStockLevelsResponse.Product)
    private static final com.ayo.inventorymanagement.GetStockLevelsResponse.Product DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ayo.inventorymanagement.GetStockLevelsResponse.Product();
    }

    public static com.ayo.inventorymanagement.GetStockLevelsResponse.Product getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Product>
        PARSER = new com.google.protobuf.AbstractParser<Product>() {
      @java.lang.Override
      public Product parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Product(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Product> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Product> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ayo.inventorymanagement.GetStockLevelsResponse.Product getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int STOCK_FIELD_NUMBER = 1;
  private java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product> stock_;
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  public java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product> getStockList() {
    return stock_;
  }
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  public java.util.List<? extends com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder> 
      getStockOrBuilderList() {
    return stock_;
  }
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  public int getStockCount() {
    return stock_.size();
  }
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  public com.ayo.inventorymanagement.GetStockLevelsResponse.Product getStock(int index) {
    return stock_.get(index);
  }
  /**
   * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
   */
  public com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder getStockOrBuilder(
      int index) {
    return stock_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < stock_.size(); i++) {
      output.writeMessage(1, stock_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < stock_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, stock_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ayo.inventorymanagement.GetStockLevelsResponse)) {
      return super.equals(obj);
    }
    com.ayo.inventorymanagement.GetStockLevelsResponse other = (com.ayo.inventorymanagement.GetStockLevelsResponse) obj;

    boolean result = true;
    result = result && getStockList()
        .equals(other.getStockList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStockCount() > 0) {
      hash = (37 * hash) + STOCK_FIELD_NUMBER;
      hash = (53 * hash) + getStockList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ayo.inventorymanagement.GetStockLevelsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ayo.inventorymanagement.GetStockLevelsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.ayo.inventorymanagement.GetStockLevelsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.ayo.inventorymanagement.GetStockLevelsResponse)
      com.ayo.inventorymanagement.GetStockLevelsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ayo.inventorymanagement.GetStockLevelsResponse.class, com.ayo.inventorymanagement.GetStockLevelsResponse.Builder.class);
    }

    // Construct using com.ayo.inventorymanagement.GetStockLevelsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStockFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stockBuilder_ == null) {
        stock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        stockBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ayo.inventorymanagement.InventoryManagementServiceProto.internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor;
    }

    @java.lang.Override
    public com.ayo.inventorymanagement.GetStockLevelsResponse getDefaultInstanceForType() {
      return com.ayo.inventorymanagement.GetStockLevelsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.ayo.inventorymanagement.GetStockLevelsResponse build() {
      com.ayo.inventorymanagement.GetStockLevelsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ayo.inventorymanagement.GetStockLevelsResponse buildPartial() {
      com.ayo.inventorymanagement.GetStockLevelsResponse result = new com.ayo.inventorymanagement.GetStockLevelsResponse(this);
      int from_bitField0_ = bitField0_;
      if (stockBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          stock_ = java.util.Collections.unmodifiableList(stock_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.stock_ = stock_;
      } else {
        result.stock_ = stockBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ayo.inventorymanagement.GetStockLevelsResponse) {
        return mergeFrom((com.ayo.inventorymanagement.GetStockLevelsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ayo.inventorymanagement.GetStockLevelsResponse other) {
      if (other == com.ayo.inventorymanagement.GetStockLevelsResponse.getDefaultInstance()) return this;
      if (stockBuilder_ == null) {
        if (!other.stock_.isEmpty()) {
          if (stock_.isEmpty()) {
            stock_ = other.stock_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStockIsMutable();
            stock_.addAll(other.stock_);
          }
          onChanged();
        }
      } else {
        if (!other.stock_.isEmpty()) {
          if (stockBuilder_.isEmpty()) {
            stockBuilder_.dispose();
            stockBuilder_ = null;
            stock_ = other.stock_;
            bitField0_ = (bitField0_ & ~0x00000001);
            stockBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStockFieldBuilder() : null;
          } else {
            stockBuilder_.addAllMessages(other.stock_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ayo.inventorymanagement.GetStockLevelsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ayo.inventorymanagement.GetStockLevelsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product> stock_ =
      java.util.Collections.emptyList();
    private void ensureStockIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        stock_ = new java.util.ArrayList<com.ayo.inventorymanagement.GetStockLevelsResponse.Product>(stock_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder, com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder> stockBuilder_;

    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product> getStockList() {
      if (stockBuilder_ == null) {
        return java.util.Collections.unmodifiableList(stock_);
      } else {
        return stockBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public int getStockCount() {
      if (stockBuilder_ == null) {
        return stock_.size();
      } else {
        return stockBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public com.ayo.inventorymanagement.GetStockLevelsResponse.Product getStock(int index) {
      if (stockBuilder_ == null) {
        return stock_.get(index);
      } else {
        return stockBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder setStock(
        int index, com.ayo.inventorymanagement.GetStockLevelsResponse.Product value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.set(index, value);
        onChanged();
      } else {
        stockBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder setStock(
        int index, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.set(index, builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder addStock(com.ayo.inventorymanagement.GetStockLevelsResponse.Product value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.add(value);
        onChanged();
      } else {
        stockBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder addStock(
        int index, com.ayo.inventorymanagement.GetStockLevelsResponse.Product value) {
      if (stockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStockIsMutable();
        stock_.add(index, value);
        onChanged();
      } else {
        stockBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder addStock(
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.add(builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder addStock(
        int index, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder builderForValue) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.add(index, builderForValue.build());
        onChanged();
      } else {
        stockBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder addAllStock(
        java.lang.Iterable<? extends com.ayo.inventorymanagement.GetStockLevelsResponse.Product> values) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, stock_);
        onChanged();
      } else {
        stockBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder clearStock() {
      if (stockBuilder_ == null) {
        stock_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        stockBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public Builder removeStock(int index) {
      if (stockBuilder_ == null) {
        ensureStockIsMutable();
        stock_.remove(index);
        onChanged();
      } else {
        stockBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder getStockBuilder(
        int index) {
      return getStockFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder getStockOrBuilder(
        int index) {
      if (stockBuilder_ == null) {
        return stock_.get(index);  } else {
        return stockBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public java.util.List<? extends com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder> 
         getStockOrBuilderList() {
      if (stockBuilder_ != null) {
        return stockBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(stock_);
      }
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder addStockBuilder() {
      return getStockFieldBuilder().addBuilder(
          com.ayo.inventorymanagement.GetStockLevelsResponse.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder addStockBuilder(
        int index) {
      return getStockFieldBuilder().addBuilder(
          index, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.getDefaultInstance());
    }
    /**
     * <code>repeated .com.ayo.inventorymanagement.GetStockLevelsResponse.Product stock = 1;</code>
     */
    public java.util.List<com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder> 
         getStockBuilderList() {
      return getStockFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.ayo.inventorymanagement.GetStockLevelsResponse.Product, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder, com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder> 
        getStockFieldBuilder() {
      if (stockBuilder_ == null) {
        stockBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.ayo.inventorymanagement.GetStockLevelsResponse.Product, com.ayo.inventorymanagement.GetStockLevelsResponse.Product.Builder, com.ayo.inventorymanagement.GetStockLevelsResponse.ProductOrBuilder>(
                stock_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        stock_ = null;
      }
      return stockBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.ayo.inventorymanagement.GetStockLevelsResponse)
  }

  // @@protoc_insertion_point(class_scope:com.ayo.inventorymanagement.GetStockLevelsResponse)
  private static final com.ayo.inventorymanagement.GetStockLevelsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ayo.inventorymanagement.GetStockLevelsResponse();
  }

  public static com.ayo.inventorymanagement.GetStockLevelsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetStockLevelsResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetStockLevelsResponse>() {
    @java.lang.Override
    public GetStockLevelsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetStockLevelsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetStockLevelsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetStockLevelsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ayo.inventorymanagement.GetStockLevelsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

