// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public final class InventoryManagementServiceProto {
  private InventoryManagementServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_GetStockLevelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_GetStockLevelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_UpdateStockRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_UpdateStockRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_UpdateStockResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_UpdateStockResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_AddProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_AddProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_inventorymanagement_AddProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_inventorymanagement_AddProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n InventoryManagementservice.proto\022\033com." +
      "ayo.inventorymanagement\"\027\n\025GetStockLevel" +
      "sRequest\"\233\001\n\026GetStockLevelsResponse\022J\n\005s" +
      "tock\030\001 \003(\0132;.com.ayo.inventorymanagement" +
      ".GetStockLevelsResponse.Product\0325\n\007Produ" +
      "ct\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010quantity" +
      "\030\003 \001(\005\"A\n\022UpdateStockRequest\022\022\n\nproduct_" +
      "id\030\001 \001(\t\022\027\n\017quantity_change\030\002 \001(\005\"\025\n\023Upd" +
      "ateStockResponse\"3\n\021AddProductRequest\022\014\n" +
      "\004name\030\001 \001(\t\022\020\n\010quantity\030\002 \001(\005\"(\n\022AddProd" +
      "uctResponse\022\022\n\nproduct_id\030\001 \001(\t2\374\002\n\032Inve" +
      "ntoryManagementService\022y\n\016GetStockLevels" +
      "\0222.com.ayo.inventorymanagement.GetStockL" +
      "evelsRequest\0323.com.ayo.inventorymanageme" +
      "nt.GetStockLevelsResponse\022t\n\013UpdateStock" +
      "\022/.com.ayo.inventorymanagement.UpdateSto" +
      "ckRequest\0320.com.ayo.inventorymanagement." +
      "UpdateStockResponse(\0010\001\022m\n\nAddProduct\022.." +
      "com.ayo.inventorymanagement.AddProductRe" +
      "quest\032/.com.ayo.inventorymanagement.AddP" +
      "roductResponseB@\n\033com.ayo.inventorymanag" +
      "ementB\037InventoryManagementServiceProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ayo_inventorymanagement_GetStockLevelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayo_inventorymanagement_GetStockLevelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_GetStockLevelsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor,
        new java.lang.String[] { "Stock", });
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor =
      internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_descriptor.getNestedTypes().get(0);
    internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_GetStockLevelsResponse_Product_descriptor,
        new java.lang.String[] { "Id", "Name", "Quantity", });
    internal_static_com_ayo_inventorymanagement_UpdateStockRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_ayo_inventorymanagement_UpdateStockRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_UpdateStockRequest_descriptor,
        new java.lang.String[] { "ProductId", "QuantityChange", });
    internal_static_com_ayo_inventorymanagement_UpdateStockResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_ayo_inventorymanagement_UpdateStockResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_UpdateStockResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_ayo_inventorymanagement_AddProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_ayo_inventorymanagement_AddProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_AddProductRequest_descriptor,
        new java.lang.String[] { "Name", "Quantity", });
    internal_static_com_ayo_inventorymanagement_AddProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_ayo_inventorymanagement_AddProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_inventorymanagement_AddProductResponse_descriptor,
        new java.lang.String[] { "ProductId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
