// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public interface UpdateStockRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.UpdateStockRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int32 quantity_change = 2;</code>
   */
  int getQuantityChange();
}
