// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: InventoryManagementservice.proto

package com.ayo.inventorymanagement;

public interface UpdateStockResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.inventorymanagement.UpdateStockResponse)
    com.google.protobuf.MessageOrBuilder {
}
