// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderProcessingService.proto

package com.ayo.orderprocessing;

public final class OrderProcessingServiceProto {
  private OrderProcessingServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_orderprocessing_ProcessOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_OrderItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_orderprocessing_ProcessOrderRequest_OrderItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_orderprocessing_ProcessOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_orderprocessing_ProcessOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034OrderProcessingService.proto\022\027com.ayo." +
      "orderprocessing\"\241\001\n\023ProcessOrderRequest\022" +
      "\020\n\010order_id\030\001 \001(\t\022E\n\005items\030\002 \003(\01326.com.a" +
      "yo.orderprocessing.ProcessOrderRequest.O" +
      "rderItem\0321\n\tOrderItem\022\022\n\nproduct_id\030\001 \001(" +
      "\t\022\020\n\010quantity\030\002 \001(\005\"9\n\024ProcessOrderRespo" +
      "nse\022\020\n\010order_id\030\001 \001(\t\022\017\n\007success\030\002 \001(\0102\373" +
      "\001\n\026OrderProcessingService\022k\n\014ProcessOrde" +
      "r\022,.com.ayo.orderprocessing.ProcessOrder" +
      "Request\032-.com.ayo.orderprocessing.Proces" +
      "sOrderResponse\022t\n\023StreamProcessOrders\022,." +
      "com.ayo.orderprocessing.ProcessOrderRequ" +
      "est\032-.com.ayo.orderprocessing.ProcessOrd" +
      "erResponse(\001B8\n\027com.ayo.orderprocessingB" +
      "\033OrderProcessingServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_orderprocessing_ProcessOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", "Items", });
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_OrderItem_descriptor =
      internal_static_com_ayo_orderprocessing_ProcessOrderRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_ayo_orderprocessing_ProcessOrderRequest_OrderItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_orderprocessing_ProcessOrderRequest_OrderItem_descriptor,
        new java.lang.String[] { "ProductId", "Quantity", });
    internal_static_com_ayo_orderprocessing_ProcessOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayo_orderprocessing_ProcessOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_orderprocessing_ProcessOrderResponse_descriptor,
        new java.lang.String[] { "OrderId", "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
