// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderProcessingService.proto

package com.ayo.orderprocessing;

public interface ProcessOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.orderprocessing.ProcessOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string order_id = 1;</code>
   */
  java.lang.String getOrderId();
  /**
   * <code>string order_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrderIdBytes();

  /**
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
