// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureService.proto

package com.ayo.temperature;

public final class TemperatureServiceProto {
  private TemperatureServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_temperature_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_temperature_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_ayo_temperature_TemperatureData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_ayo_temperature_TemperatureData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030TemperatureService.proto\022\023com.ayo.temp" +
      "erature\"\024\n\022TemperatureRequest\"&\n\017Tempera" +
      "tureData\022\023\n\013temperature\030\001 \001(\0012z\n\022Tempera" +
      "tureService\022d\n\021StreamTemperature\022\'.com.a" +
      "yo.temperature.TemperatureRequest\032$.com." +
      "ayo.temperature.TemperatureData0\001B0\n\023com" +
      ".ayo.temperatureB\027TemperatureServiceProt" +
      "oP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_ayo_temperature_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_ayo_temperature_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_temperature_TemperatureRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_ayo_temperature_TemperatureData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_ayo_temperature_TemperatureData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_ayo_temperature_TemperatureData_descriptor,
        new java.lang.String[] { "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
