// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureService.proto

package com.ayo.temperature;

public interface TemperatureDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.temperature.TemperatureData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
