// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureService.proto

package com.ayo.temperature;

public interface TemperatureDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.temperature.TemperatureData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
