// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureService.proto

package com.ayo.temperature;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.ayo.temperature.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {
}
